form
Navaruz22/Market-2 pull request #223
Opened 2022-08-24 07:57 UTC by Dilsuz07

**Issue #:** [JIRA-ALO24](https://alo24.atlassian.net/jira/software/projects/L24/boards/5)

## PR turi

PR'da qanday turdagi o'zgarish bo'lganini belgilang:

- [ ] Xatolik tuzatildi
- [ ] Yangi vazifa bajarildi
- [ ] Kod stilida o'zgarishlar (formatting, renaming)
- [ ] Funksional o'zgarishlar
- [ ] Boshqa:

## PR ko'lami

Bu PR quyidagi file'larga yangi kod qo'shgan, yoki o'zgartirish kiritgan:

- Yangi - Component A
- O'zgartirish - Page B
- O'zgaritirish - Component C

## Screenshots

#### oldingi holati:

#### hozirgi holati:

## Avvalgi holatni tasvirlang

- foo

## Hozirgi holatni tasvirlang
SearchInputlardagi xatolar to'g'irlandi.  Faqat Inter bosilganda ayrim pagelarda backend yozilmagani uchun so'rov ketmaydi(Ketegoriya)
- bar

## Bu PR keskin o'zgarishlar keltirib chiqaradimi?

- [ ] Ha (tushuntirish bering):
- [ ] Yo'q

## Boshqa ma'lumotlar

Qo'shimcha ma'lumotlarni shu yerda qoldirishingiz mumkun

## Pull request checklist

PR quyidagilardan qaysi biriga to'g'ri kelsa, belgilab chiqing:

- [ ] Feature branch'ni master branch bilan up-to-date saqlash uchun rebase
      ishlatildi. Boshqacha qilib aytganda, PR raise qilishdan avval rebase
      qilingan

2022-08-24 10:17 UTC, sarvar9417 requested changes

2022-08-24 10:17 UTC, sarvar9417 commented on server/routers/sales/client.js
> +      .populate({ path: "packman", match: { name: packman }, select: 'name'})
Backendga nega tegindizgiz

2022-08-24 11:11 UTC, Dilsuz07 commented on server/routers/sales/client.js
> +      .populate({ path: "packman", match: { name: packman }, select: 'name'})
haa

2022-08-26 05:17 UTC, sarvar9417 approved these changes

2022-08-26 05:18 UTC, merged